modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/SheepSqueak/issues"
license="MIT"

[[mods]]
modId="sheepsqueak"
version="${file.jarVersion}"
displayName="Sheep Squeak"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sheep-squeak"
authors="ShyNieke, Mrbysco"
description='''
Squeaky squeak
'''
[[dependencies.sheepsqueak]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"