modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/SheepSqueak/issues"
license="MIT"

[[mods]]
modId="sheepsqueak"
version="${file.jarVersion}"
displayName="Sheep Squeak"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sheep-squeak"
authors="ShyNieke, Mrbysco"
description='''
Squeaky squeak
'''
[[dependencies.sheepsqueak]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.sheepsqueak]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"