modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/SheepSqueak/issues"
license="MIT"

[[mods]]
modId="sheepsqueak"
version="${file.jarVersion}"
displayName="Sheep Squeak"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sheep-squeak"
authors="ShyNieke, Mrbysco"
description='''
Squeaky squeak
'''
[[dependencies.sheepsqueak]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.sheepsqueak]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"